version: "3"
services:
  jekyll:
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      # This protects the gems from being "deleted" by your local mount
      - vendor_bundle:/usr/local/bundle 

volumes:
  vendor_bundle: